name: Actions Workflow
# actions permite llamar a otro repositorio y ejecutar acciones 
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls 
          echo "commit     : $GITHUB_SHA"
          echo "repository : $GITHUB_REPOSITORY"
          echo "workspace  : $GITHUB_WORKSPACE"

        # see https://docs.github.com/es/actions/learn-github-actions/environment-variables#default-environment-variables
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After checkout
        run: |
          pwd
          ls 
      # por default no clona el repo al contenedor para ejecutar la tarea, debemos especificar que archivos utilizar
      - name: "Simple JS Actions Workflow"
        id: greet
      # los actions se pueden realizar apuntando a un archivo inverno o en otro repositorio
        uses: actions/hello-world-javascript-action@v1  # user/project@[branh, commit or version] 
        with:
          who-to-greet: "Luis Vasquez"
      - name: Log Geetin Time
        run: echo {{steps.greet.outputs.time}}
