name : Encriptions files
on: push
jobs:

  decript:
    runs-on: ubuntu-latest
    steps:
      - name: Decript file
        run: gpg --quiet --batch --yes --decrypt --passphrase="{{ secrets.MY_PRHASE_GPG}}" --output $HOME/personal_secret.json personal_secret.json.gpg

      - name: "check file content"
        run: cat $HOME/personal_secret.json

# https://www.gnupg.org/download/index.html
# https://docs.github.com/en/actions/security-guides/encrypted-secrets